### ISSUE TITLE
Might be easier this way

### ISSUE THREAD

**Issue by asottile** [cclauss/TravisCI-with-both-Go-and-Python#1]
https://github.com/asottile/setuptools-golang/blob/master/.travis.yml

**Comment by cclauss** [comment]
Thanks massively!  I will give it a spin tomorrow.

**Comment by asottile** [comment]
Or this one, if you also need to have a functioning gopath: https://github.com/asottile/dockerfile/blob/master/.travis.yml

**Comment by asottile** [comment]
Marking this as fixed!
